import React, { useState, useEffect } from 'react';
import { AlertTriangle, ShieldAlert, CheckCircle2, Filter, Check } from 'lucide-react';
import { useApp } from '../context/AppContext';
import { useAuth } from '../context/AuthContext';
import api from '../services/api';

export default function Alerts() {
  const { user } = useAuth();
  const { globalSearch, addToast, refreshTrigger } = useApp();
  const [alerts, setAlerts] = useState([]);
  const [severityFilter, setSeverityFilter] = useState('All');
  const [loading, setLoading] = useState(true);

  const fetchAlerts = async () => {
    try {
      const res = await api.get('/alerts');
      setAlerts(res.data);
    } catch (e) {
      // ignore
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchAlerts();
  }, [refreshTrigger]);

  const handleResolve = async (id) => {
    try {
      await api.post(`/alerts/${id}/resolve`);
      addToast('Alert Resolved', `Resolved alert #${id}`, 'success');
      fetchAlerts();
    } catch (err) {
      addToast('Error', 'Failed to resolve alert', 'critical');
    }
  };

  const handleResolveAll = async () => {
    try {
      const res = await api.post('/alerts/resolve-all');
      addToast('All Resolved', res.data.message, 'success');
      fetchAlerts();
    } catch (err) {
      addToast('Error', 'Failed to resolve alerts', 'critical');
    }
  };

  const filteredAlerts = alerts.filter((a) => {
    const matchesSearch =
      a.message.toLowerCase().includes(globalSearch.toLowerCase()) ||
      a.agent_name.toLowerCase().includes(globalSearch.toLowerCase()) ||
      a.alert_type.toLowerCase().includes(globalSearch.toLowerCase());

    const matchesSeverity = severityFilter === 'All' || a.severity === severityFilter;
    return matchesSearch && matchesSeverity;
  });

  return (
    <div className="p-6 space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-xl font-bold text-white tracking-tight flex items-center gap-2">
            <AlertTriangle className="w-5 h-5 text-amber-400" /> Alert & Policy Audit Center
          </h1>
          <p className="text-xs text-gray-400 mt-0.5">Real-time alert notifications generated by Policy Engine</p>
        </div>

        <div className="flex items-center gap-3">
          {/* Severity filter */}
          <div className="flex items-center gap-1 bg-gray-900/80 border border-gray-800 p-1 rounded-xl">
            {['All', 'Info', 'Warning', 'High', 'Critical'].map((sev) => (
              <button
                key={sev}
                onClick={() => setSeverityFilter(sev)}
                className={`px-3 py-1 rounded-lg text-xs font-semibold transition-colors ${
                  severityFilter === sev ? 'bg-blue-600 text-white shadow-glow-blue' : 'text-gray-400 hover:text-gray-200'
                }`}
              >
                {sev}
              </button>
            ))}
          </div>

          {(user?.role === 'Admin' || user?.role === 'Manager') && (
            <button
              onClick={handleResolveAll}
              className="px-3.5 py-1.5 rounded-xl bg-emerald-600/20 hover:bg-emerald-600/30 border border-emerald-500/30 text-emerald-300 font-semibold text-xs transition-all flex items-center gap-1.5"
            >
              <Check className="w-3.5 h-3.5" /> Resolve All
            </button>
          )}
        </div>
      </div>

      {/* Alerts List */}
      <div className="space-y-3">
        {filteredAlerts.map((a) => (
          <div
            key={a.alert_id}
            className={`glass-card rounded-2xl p-4 flex flex-col sm:flex-row sm:items-center justify-between gap-4 border ${
              a.is_resolved
                ? 'opacity-60 border-gray-800'
                : a.severity === 'Critical'
                ? 'border-red-500/40 bg-red-950/10'
                : a.severity === 'High'
                ? 'border-amber-500/40 bg-amber-950/10'
                : 'border-blue-500/30'
            }`}
          >
            <div className="flex items-start gap-3">
              <AlertTriangle
                className={`w-5 h-5 shrink-0 mt-0.5 ${
                  a.severity === 'Critical'
                    ? 'text-red-400'
                    : a.severity === 'High'
                    ? 'text-amber-400'
                    : 'text-blue-400'
                }`}
              />
              <div className="space-y-1">
                <div className="flex items-center gap-2">
                  <span
                    className={`px-2 py-0.5 rounded text-[10px] font-bold uppercase ${
                      a.severity === 'Critical'
                        ? 'bg-red-500/20 text-red-400'
                        : a.severity === 'High'
                        ? 'bg-amber-500/20 text-amber-400'
                        : 'bg-blue-500/20 text-blue-400'
                    }`}
                  >
                    {a.severity}
                  </span>
                  <span className="font-bold text-xs text-white">{a.alert_type}</span>
                  <span className="text-[10px] text-gray-500 font-mono">
                    {new Date(a.timestamp).toLocaleString()}
                  </span>
                </div>
                <p className="text-xs text-gray-300">{a.message}</p>
                <div className="text-[10px] text-gray-500 font-mono">Target Agent: {a.agent_name} ({a.team_name})</div>
              </div>
            </div>

            <div className="flex items-center gap-2">
              {a.is_resolved ? (
                <span className="text-[11px] font-bold text-emerald-400 flex items-center gap-1">
                  <CheckCircle2 className="w-3.5 h-3.5" /> Resolved
                </span>
              ) : (
                (user?.role === 'Admin' || user?.role === 'Manager') && (
                  <button
                    onClick={() => handleResolve(a.alert_id)}
                    className="px-3 py-1.5 rounded-lg bg-gray-800 hover:bg-gray-700 text-gray-300 text-xs font-medium transition-colors"
                  >
                    Mark Resolved
                  </button>
                )
              )}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
